---
- name: Install unattended-upgrades package.
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes
  tags:
    - apt
    - unattended-upgrades

- name: Configure unattended-upgrades to update the packages from sources.list.
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    owner: root
    group: root
  tags:
    - apt
    - unattended-upgrades

- name: Configure unattended-upgrades to update the packages from sources.list.
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    owner: root
    group: root
  tags:
    - apt
    - unattended-upgrades
